# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-31 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poke_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokes_received', to='login.User')),
                ('poke_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokes_sent', to='login.User')),
            ],
        ),
    ]
